### ISSUE TITLE
BigCommerce API

### ISSUE THREAD

**Issue by neilbradley** [TopShelfCraft/Legacy-Login#1]
Hey Michael,

Just wanted to check if your plugin requires the BigCommerce account to be left open and using their API for a period after migrating to Craft so that customers get logged in to the new Craft site?

The reason I ask is that we did something similar for Magento so that when existing BigCommerce customers logged into the new Magento site, we did an BigCommerce API lookup in the background and converted their password to a Magento secured one.

I thought it might just be worth mentioning on the instructions if yours relies on the BC account and API to remain active. :) Admittedly I haven't installed the plugin, so it maybe mentions it inside. :)

**Comment by michaelrog** [comment]
The BigCommerce authenticator currently included in _Legacy Login_ is made to work with older, self-hosted versions of BigCommerce, where user data was stored in a database table and passwords were hashed w/ MD5. (This was prior to their hosted solution, and before their adoption of oAuth.)
