### ISSUE TITLE
Port WordPress login driver to 3.x (Craft 3) version

### ISSUE THREAD

**Issue by green17** [TopShelfCraft/Legacy-Login#9]
Can the Craft 3 version of Legacy Login authenticate users from WordPress?

**Comment by michaelrog** [comment]
Hi @green17 — I haven't ported the WordPress driver to Craft 3 yet, but it's primed and ready as soon as a client sponsors the development. You interested?

**Comment by green17** [comment]
@michaelrog we don't yet have a request for it just looking at a project it might be handy for. How much time would it take?

**Comment by michaelrog** [comment]
Assuming you're bringing a database for testing, I estimate it'd take ~2 hours of dev to port the WordPress driver.

**Comment by green17** [comment]
Sounds good leave it with me, I will let you know if it goes ahead. :-)

**Comment by michaelrog** [comment]
The WordPress driver is available in Legacy Login `4.x` and `5.x`.
